algo = (input('Digite algo:'))
print('O tipo primitivo é: {} ' .format(type(algo)))  
print('Só tem espaços? {}' .format(algo.isspace())) 
print('É um número? {}' .format(algo.isnumeric()))
print('É alfebetico? {}' .format(algo.isalpha()))
print('É alfanumerico ? {}' .format(algo.isalnum()))
print('Está em maiuscula? {}' .format(algo.isupper()))
print('Está em minuscula? {}' .format(algo.islower()))
print('Está em capitalizada? {}' .format(algo.istitle()))